#pragma once // Inclusion une seule fois
// #include "ECS.h"
#include "Entity.hpp"
// #include "TransformComponent.h"
// #include "SpriteComponent.h"
// #include "KeyboardController.h"
// #include "ColliderComponent.h"
// #include "TileComponent.h"
// #include "ProjectileComponent.h"
// #include "UILabel.h"